[defaults]
user = "root"
guest_user = "root"
identity_file = "~/.ssh/proxmox"
guest_identity_file = "~/.ssh/guest"
ssh_extra_args = []
guest_ssh_extra_args = []
max_parallel = 2
dry_run = true

[[hosts]]
name = "example"
host = "proxmox.example.com"
